# Generated by Django 5.0.3 on 2024-04-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
    ]
