# Generated by Django 5.0.3 on 2024-04-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_blogpost_id_alter_comment_id_alter_profile_id"),
        ("home", "0005_remove_blogpost_video"),
    ]

    operations = []
